// This file is auto-generated by @hey-api/openapi-ts

export type GetMoviesDto = {
    movies: Array<{
        id: number;
        title: string;
        releaseYear: number;
        availability: Array<{
            streamingService: {
                id: number;
                name: string;
                logoUrl: string;
            };
        }>;
    }>;
};

export type MovieDto = {
    id: number;
    title: string;
    releaseYear: number;
    availability: Array<{
        streamingService: {
            id: number;
            name: string;
            logoUrl: string;
        };
    }>;
};

export type CreateMovieDto = {
    title: string;
    releaseYear: number;
    availability: Array<{
        streamingServiceId: number;
        country: string;
    }>;
};

export type GetStreamingServicesDto = {
    streamingServices: Array<{
        id: number;
        name: string;
        logoUrl: string;
        availability: Array<{
            movie: {
                id: number;
                title: string;
                releaseYear: number;
            };
        }>;
    }>;
};

export type StreamingServiceDto = {
    id: number;
    name: string;
    logoUrl: string;
    availability: Array<{
        movie: {
            id: number;
            title: string;
            releaseYear: number;
        };
    }>;
};

export type CreateStreamingServiceDto = {
    name: string;
    logoUrl: string;
};

export type CreateApplicationDto = {
    name: string;
};

export type ApplicationDto = {
    id: string;
    name: string;
    apiKey: string;
};

export type GetAuthGoogleResponse = unknown;

export type GetAuthGoogleCallbackResponse = unknown;

export type PostAuthRefreshResponse = unknown;

export type GetMoviesData = {
    country: string;
};

export type GetMoviesResponse = GetMoviesDto;

export type PostMoviesData = {
    requestBody: CreateMovieDto;
};

export type PostMoviesResponse = MovieDto;

export type GetMoviesByIdData = {
    country: string;
    id: number;
};

export type GetMoviesByIdResponse = MovieDto;

export type GetStreamingServicesData = {
    country: string;
};

export type GetStreamingServicesResponse = GetStreamingServicesDto;

export type PostStreamingServicesData = {
    requestBody: CreateStreamingServiceDto;
};

export type PostStreamingServicesResponse = StreamingServiceDto;

export type GetStreamingServicesByIdData = {
    country: string;
    id: number;
};

export type GetStreamingServicesByIdResponse = StreamingServiceDto;

export type PostApplicationsData = {
    requestBody: CreateApplicationDto;
};

export type PostApplicationsResponse = ApplicationDto;

export type GetApplicationsResponse = ApplicationDto;

export type GetApplicationsByIdData = {
    id: string;
};

export type GetApplicationsByIdResponse = ApplicationDto;

export type $OpenApiTs = {
    '/auth/google': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/auth/google/callback': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/auth/refresh': {
        post: {
            res: {
                201: unknown;
            };
        };
    };
    '/movies': {
        get: {
            req: GetMoviesData;
            res: {
                200: GetMoviesDto;
            };
        };
        post: {
            req: PostMoviesData;
            res: {
                201: MovieDto;
            };
        };
    };
    '/movies/{id}': {
        get: {
            req: GetMoviesByIdData;
            res: {
                200: MovieDto;
            };
        };
    };
    '/streaming-services': {
        get: {
            req: GetStreamingServicesData;
            res: {
                200: GetStreamingServicesDto;
            };
        };
        post: {
            req: PostStreamingServicesData;
            res: {
                201: StreamingServiceDto;
            };
        };
    };
    '/streaming-services/{id}': {
        get: {
            req: GetStreamingServicesByIdData;
            res: {
                200: StreamingServiceDto;
            };
        };
    };
    '/applications': {
        post: {
            req: PostApplicationsData;
            res: {
                201: ApplicationDto;
            };
        };
        get: {
            res: {
                201: ApplicationDto;
            };
        };
    };
    '/applications/{id}': {
        get: {
            req: GetApplicationsByIdData;
            res: {
                201: ApplicationDto;
            };
        };
    };
};