// This file is auto-generated by @hey-api/openapi-ts

export type GetMoviesDto = {
    movies: Array<{
        id: number;
        title: string;
        releaseYear: number;
        availability: Array<{
            streamingService: {
                id: number;
                name: string;
                logoUrl: string;
            };
            upvotes?: number;
            downvotes?: number;
        }>;
    }>;
};

export type MovieDto = {
    id: number;
    title: string;
    releaseYear: number;
    availability: Array<{
        streamingService: {
            id: number;
            name: string;
            logoUrl: string;
        };
        upvotes?: number;
        downvotes?: number;
    }>;
};

export type CreateMovieDto = {
    title: string;
    releaseYear: number;
    availability: Array<{
        streamingServiceId: number;
        country: string;
    }>;
};

export type AddMovieAvailabilityDto = {
    streamingServiceId: number;
    country: string;
};

export type VoteAvailabilityDto = {
    movieAvailabilityId: number;
    isUpvote: boolean;
};

export type VoteResponseDto = {
    movieAvailabilityId: number;
    upvotes: number;
    downvotes: number;
    success: boolean;
};

export type GetStreamingServicesDto = {
    streamingServices: Array<{
        id: number;
        name: string;
        logoUrl: string;
        availability: Array<{
            movie: {
                id: number;
                title: string;
                releaseYear: number;
            };
        }>;
    }>;
};

export type StreamingServiceDto = {
    id: number;
    name: string;
    logoUrl: string;
    availability: Array<{
        movie: {
            id: number;
            title: string;
            releaseYear: number;
        };
    }>;
};

export type CreateStreamingServiceDto = {
    name: string;
    logoUrl: string;
};

export type CreateApplicationDto = {
    /**
     * Application name
     */
    name: string;
};

export type ApplicationDto = {
    /**
     * Application ID
     */
    id: string;
    /**
     * Application name
     */
    name: string;
    /**
     * API key (only returned when creating a new application)
     */
    apiKey?: string;
    /**
     * List of API keys for this application
     */
    apiKeys?: Array<{
        /**
         * API key ID
         */
        id: number;
        /**
         * API key name
         */
        name: string;
        /**
         * Whether the API key is enabled
         */
        enabled: boolean;
        /**
         * When the API key was created
         */
        createdAt: string;
        /**
         * The API key value (only provided when creating new keys)
         */
        key?: string;
    }>;
};

export type GetApplicationsDto = {
    /**
     * List of user applications
     */
    applications: Array<{
        /**
         * Application ID
         */
        id: string;
        /**
         * Application name
         */
        name: string;
        /**
         * API key (only returned when creating a new application)
         */
        apiKey?: string;
        /**
         * List of API keys for this application
         */
        apiKeys?: Array<{
            /**
             * API key ID
             */
            id: number;
            /**
             * API key name
             */
            name: string;
            /**
             * Whether the API key is enabled
             */
            enabled: boolean;
            /**
             * When the API key was created
             */
            createdAt: string;
            /**
             * The API key value (only provided when creating new keys)
             */
            key?: string;
        }>;
    }>;
};

export type CreateApiKeyDto = {
    /**
     * Name of the API key
     */
    name?: string;
};

export type ApiKeyDto = {
    /**
     * API key ID
     */
    id: number;
    /**
     * API key name
     */
    name: string;
    /**
     * Whether the API key is enabled
     */
    enabled: boolean;
    /**
     * When the API key was created
     */
    createdAt: string;
    /**
     * The API key value (only provided when creating new keys)
     */
    key?: string;
};

export type GetAuthGoogleResponse = unknown;

export type GetAuthGoogleCallbackResponse = unknown;

export type PostAuthRefreshResponse = unknown;

export type GetMoviesData = {
    country: string;
};

export type GetMoviesResponse = GetMoviesDto;

export type PostMoviesData = {
    requestBody: CreateMovieDto;
};

export type PostMoviesResponse = MovieDto;

export type GetMoviesByIdData = {
    country: string;
    id: number;
};

export type GetMoviesByIdResponse = MovieDto;

export type PostMoviesByIdAvailabilityData = {
    id: number;
    requestBody: AddMovieAvailabilityDto;
};

export type PostMoviesByIdAvailabilityResponse = MovieDto;

export type PostMoviesByIdAvailabilityVoteData = {
    requestBody: VoteAvailabilityDto;
};

export type PostMoviesByIdAvailabilityVoteResponse = VoteResponseDto;

export type GetStreamingServicesData = {
    country: string;
};

export type GetStreamingServicesResponse = GetStreamingServicesDto;

export type PostStreamingServicesData = {
    requestBody: CreateStreamingServiceDto;
};

export type PostStreamingServicesResponse = StreamingServiceDto;

export type GetStreamingServicesByIdData = {
    country: string;
    id: number;
};

export type GetStreamingServicesByIdResponse = StreamingServiceDto;

export type PostApplicationsData = {
    requestBody: CreateApplicationDto;
};

export type PostApplicationsResponse = ApplicationDto;

export type GetApplicationsResponse = GetApplicationsDto;

export type GetApplicationsByIdData = {
    id: string;
};

export type GetApplicationsByIdResponse = unknown;

export type DeleteApplicationsByIdData = {
    id: string;
};

export type DeleteApplicationsByIdResponse = unknown;

export type PostApplicationsByIdApiKeysData = {
    id: string;
    requestBody: CreateApiKeyDto;
};

export type PostApplicationsByIdApiKeysResponse = ApiKeyDto;

export type PatchApplicationsByIdApiKeysByKeyData = {
    id: string;
    key: string;
};

export type PatchApplicationsByIdApiKeysByKeyResponse = ApiKeyDto;

export type DeleteApplicationsByIdApiKeysByKeyData = {
    id: string;
    key: string;
};

export type DeleteApplicationsByIdApiKeysByKeyResponse = unknown;

export type $OpenApiTs = {
    '/auth/google': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/auth/google/callback': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/auth/refresh': {
        post: {
            res: {
                201: unknown;
            };
        };
    };
    '/movies': {
        get: {
            req: GetMoviesData;
            res: {
                200: GetMoviesDto;
            };
        };
        post: {
            req: PostMoviesData;
            res: {
                201: MovieDto;
            };
        };
    };
    '/movies/{id}': {
        get: {
            req: GetMoviesByIdData;
            res: {
                200: MovieDto;
            };
        };
    };
    '/movies/{id}/availability': {
        post: {
            req: PostMoviesByIdAvailabilityData;
            res: {
                201: MovieDto;
            };
        };
    };
    '/movies/{id}/availability/vote': {
        post: {
            req: PostMoviesByIdAvailabilityVoteData;
            res: {
                201: VoteResponseDto;
            };
        };
    };
    '/streaming-services': {
        get: {
            req: GetStreamingServicesData;
            res: {
                200: GetStreamingServicesDto;
            };
        };
        post: {
            req: PostStreamingServicesData;
            res: {
                201: StreamingServiceDto;
            };
        };
    };
    '/streaming-services/{id}': {
        get: {
            req: GetStreamingServicesByIdData;
            res: {
                200: StreamingServiceDto;
            };
        };
    };
    '/applications': {
        post: {
            req: PostApplicationsData;
            res: {
                201: ApplicationDto;
            };
        };
        get: {
            res: {
                default: GetApplicationsDto;
            };
        };
    };
    '/applications/{id}': {
        get: {
            req: GetApplicationsByIdData;
            res: {
                200: unknown;
            };
        };
        delete: {
            req: DeleteApplicationsByIdData;
            res: {
                200: unknown;
            };
        };
    };
    '/applications/{id}/api-keys': {
        post: {
            req: PostApplicationsByIdApiKeysData;
            res: {
                201: ApiKeyDto;
            };
        };
    };
    '/applications/{id}/api-keys/{key}': {
        patch: {
            req: PatchApplicationsByIdApiKeysByKeyData;
            res: {
                default: ApiKeyDto;
            };
        };
        delete: {
            req: DeleteApplicationsByIdApiKeysByKeyData;
            res: {
                200: unknown;
            };
        };
    };
};